/*
 * noakcalculator(TM) is a Java program that provides a high-precision scientific calculator
 * Copyright (C) 2019-25 quark95cos
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package noakcalc.gui;

import java.awt.Font;
import java.awt.event.MouseListener;
import java.util.Iterator;
import java.util.Set;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameTitlePane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import noakcalc.Utilities.CalcConstants;
import noakcalc.Utilities.Configs;
import noakcalc.Utilities.KeyBrdInputHandler;
import noakcalc.Utilities.MiscConstants;
import noakcalc.components.Calculator;
import noakutils.UtilsMisc;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 *
 * SubCalculator Class Extends javax.swing.JInternalFrame
 */
public class SubCalculator extends javax.swing.JInternalFrame {

    private boolean is2ndclicked;
    private String numMode;
    private String[] propSplitStrings;
    private JPopupMenu popupMenu = new JPopupMenu();
    private Configs constantProps;
    private final Calculator calc;
    private final KeyBrdInputHandler keyBrdInputHandler;
    private final java.util.ResourceBundle numberBundle =
            java.util.ResourceBundle.getBundle(MiscConstants.NUMBER_BUNDLE_NAME);
    private final java.util.ResourceBundle operatorBundle =
            java.util.ResourceBundle.getBundle(MiscConstants.OPERATOR_BUNDLE_NAME);
    private final java.util.ResourceBundle miscBundle =
            java.util.ResourceBundle.getBundle(MiscConstants.MISC_BUNDLE_NAME);
    private final java.util.ResourceBundle functionBundle =
            java.util.ResourceBundle.getBundle(MiscConstants.FUNCTION_BUNDLE_NAME);
    private final java.util.ResourceBundle constantBundle =
            java.util.ResourceBundle.getBundle(MiscConstants.CONSTANT_BUNDLE_NAME);

    private static final Logger LOGGER =
        LogManager.getLogger(SubCalculator.class.getName());

    /**
     * Creates new form SubCalculator
     *
     */
    public SubCalculator() {
        this.is2ndclicked = false;
        this.numMode = null;
        this.popupMenu = new JPopupMenu();
        this.calc = new Calculator();
        this.keyBrdInputHandler = new KeyBrdInputHandler(this);
        initComponents();
        init();
        //init stuff was here
    }

    private void init() {
        //java.util.ResourceBundle.getBundle("noakcalc/data/text/number").getString("zero");
        //java.util.ResourceBundle.getBundle("noakcalc/data/text/number").getString("one");
        //java.util.ResourceBundle.getBundle("noakcalc/data/text/number").getString("two");
        jtxtPrimary.addKeyListener(keyBrdInputHandler);
        jtxtSecondary.setFocusable(false);
        jtxtAreaOutput.setFocusable(false);
        setNumMode(CalcConstants.DEC);
        jrdioBtnDec.setSelected(true);
        BasicInternalFrameUI basicInternalFrameUI = ((BasicInternalFrameUI) this.getUI());
        for (MouseListener listener: basicInternalFrameUI.getNorthPane().getMouseListeners()) {
            basicInternalFrameUI.getNorthPane().removeMouseListener(listener);
        }
        //basicInternalFrameUI.setNorthPane(null);
        //this.setBorder(null);
        BasicInternalFrameTitlePane titlePane = (BasicInternalFrameTitlePane)
                ((BasicInternalFrameUI) this.getUI()).getNorthPane();
        //titlePane.setEnabled(false);
        //titlePane.removeAll();
        this.remove(titlePane);
        //this.setBorder(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnGrpBase = new javax.swing.ButtonGroup();
        jtxtSecondary = new javax.swing.JTextField();
        jtxtPrimary = new javax.swing.JTextField();
        jbtnBackspace = new javax.swing.JButton();
        jbtnClear = new javax.swing.JButton();
        jbtnClearEntry = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn7 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jbtnA = new javax.swing.JButton();
        jbtnB = new javax.swing.JButton();
        jbtnC = new javax.swing.JButton();
        jbtnD = new javax.swing.JButton();
        jbtnE = new javax.swing.JButton();
        jbtnF = new javax.swing.JButton();
        jbtnDecimal = new javax.swing.JButton();
        jbtnNegate = new javax.swing.JButton();
        jbtnAdd = new javax.swing.JButton();
        jbtnModulus = new javax.swing.JButton();
        jbtnInverse = new javax.swing.JButton();
        jbtnSubtract = new javax.swing.JButton();
        jbtnMemClear = new javax.swing.JButton();
        jbtnOpenBracket = new javax.swing.JButton();
        jbtnDivide = new javax.swing.JButton();
        jbtnMemRecall = new javax.swing.JButton();
        jbtnCloseBracket = new javax.swing.JButton();
        jbtnMultiply = new javax.swing.JButton();
        jbtnMemPlus = new javax.swing.JButton();
        jbtnFactorial = new javax.swing.JButton();
        jbtnEqual = new javax.swing.JButton();
        jbtnMemMinus = new javax.swing.JButton();
        jbtnLog = new javax.swing.JButton();
        jbtnSin = new javax.swing.JButton();
        jbtnCsc = new javax.swing.JButton();
        jbtnCos = new javax.swing.JButton();
        jbtnSec = new javax.swing.JButton();
        jbtnTan = new javax.swing.JButton();
        jbtnCot = new javax.swing.JButton();
        jbtnExpTen = new javax.swing.JButton();
        jbtnXPowerY = new javax.swing.JButton();
        jbtnNRootX = new javax.swing.JButton();
        jbtnExpPowerX = new javax.swing.JButton();
        jbtnXPower2 = new javax.swing.JButton();
        jbtnSquareRoot = new javax.swing.JButton();
        jbtnRoundFloor = new javax.swing.JButton();
        jbtnXPower3 = new javax.swing.JButton();
        jbtnCubeRoot = new javax.swing.JButton();
        jbtnRoundCeiling = new javax.swing.JButton();
        jbtnLn = new javax.swing.JButton();
        jbtnMemSet = new javax.swing.JButton();
        jbtnInt = new javax.swing.JButton();
        jbtnDMS = new javax.swing.JButton();
        jbtnConstDropDown = new javax.swing.JButton();
        jbtn2nd = new javax.swing.JButton();
        jbtnClearOutput = new javax.swing.JButton();
        jpnlDisplay = new javax.swing.JPanel();
        jlbl2nd = new javax.swing.JLabel();
        jlblMem = new javax.swing.JLabel();
        jrdioBtnHex = new javax.swing.JRadioButton();
        jrdioBtnDec = new javax.swing.JRadioButton();
        jrdioBtnOct = new javax.swing.JRadioButton();
        jrdioBtnBin = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtAreaOutput = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(980, 520));

        jtxtSecondary.setFont(new Font("Arial", Font.BOLD, 18));
        jtxtSecondary.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jtxtPrimary.setFont(new Font("Arial", Font.BOLD, 18));
        jtxtPrimary.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtPrimary.setText("0");

        jbtnBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnClearEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnF.setPreferredSize(new java.awt.Dimension(54, 32));
        jbtnF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnNegate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnModulus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnInverse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnMemClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnOpenBracket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnMemRecall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnCloseBracket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnMemPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnMemMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnCsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnCot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnExpTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnXPowerY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnNRootX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnExpPowerX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnXPower2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnSquareRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnRoundFloor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnXPower3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnCubeRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnRoundCeiling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnLn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnMemSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnDMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeyActionPerformed(evt);
            }
        });

        jbtnConstDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConstDropDownActionPerformed(evt);
            }
        });

        jbtn2nd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ndjbtnKeyActionPerformed(evt);
            }
        });

        jbtnClearOutput.setText("CLEAR OUTPUT");
        jbtnClearOutput.setToolTipText("Clear Output");
        jbtnClearOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearOutputActionPerformed(evt);
            }
        });

        jpnlDisplay.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jlbl2nd.setEnabled(false);

        jlblMem.setEnabled(false);

        javax.swing.GroupLayout jpnlDisplayLayout = new javax.swing.GroupLayout(jpnlDisplay);
        jpnlDisplay.setLayout(jpnlDisplayLayout);
        jpnlDisplayLayout.setHorizontalGroup(
            jpnlDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbl2nd, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlblMem)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jpnlDisplayLayout.setVerticalGroup(
            jpnlDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl2nd)
                    .addComponent(jlblMem))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        setObjectFromProp(jlbl2nd, miscBundle.getString(MiscConstants.WEN), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jlblMem, miscBundle.getString(MiscConstants.MME), MiscConstants.PIPE_DELIMITER);

        jbtnGrpBase.add(jrdioBtnHex);
        jrdioBtnHex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdioBtnActionPerformed(evt);
            }
        });

        jbtnGrpBase.add(jrdioBtnDec);
        jrdioBtnDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdioBtnActionPerformed(evt);
            }
        });

        jbtnGrpBase.add(jrdioBtnOct);
        jrdioBtnOct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdioBtnActionPerformed(evt);
            }
        });

        jbtnGrpBase.add(jrdioBtnBin);
        jrdioBtnBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdioBtnActionPerformed(evt);
            }
        });

        jtxtAreaOutput.setColumns(20);
        jtxtAreaOutput.setFont(new Font("Arial", Font.BOLD, 14));
        jtxtAreaOutput.setRows(5);
        jScrollPane1.setViewportView(jtxtAreaOutput);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtSecondary)
                            .addComponent(jtxtPrimary))
                        .addGap(18, 18, 18)
                        .addComponent(jpnlDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jbtnBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtnDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtnNegate, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbtnClearEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrdioBtnHex)
                                    .addComponent(jrdioBtnOct))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrdioBtnDec)
                                    .addComponent(jrdioBtnBin))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jbtnB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnModulus, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                                .addComponent(jbtnSubtract, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbtnMultiply, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbtnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtnMemRecall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbtnMemSet, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnMemPlus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbtnMemMinus, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jbtnConstDropDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbtnMemClear, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                .addComponent(jbtn2nd, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnOpenBracket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnInverse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnCloseBracket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnFactorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnInt, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnDMS, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnExpTen, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnXPowerY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnXPower2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnXPower3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnLn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnSin)
                            .addComponent(jbtnCos)
                            .addComponent(jbtnTan)
                            .addComponent(jbtnNRootX)
                            .addComponent(jbtnSquareRoot)
                            .addComponent(jbtnCubeRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnCsc)
                            .addComponent(jbtnSec)
                            .addComponent(jbtnCot)
                            .addComponent(jbtnExpPowerX, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnRoundCeiling, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                            .addComponent(jbtnRoundFloor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtnClearOutput)
                        .addGap(74, 74, 74))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbtn0, jbtn1, jbtn2, jbtn3, jbtn4, jbtn5, jbtn6, jbtn7, jbtn8, jbtn9, jbtnAdd, jbtnBackspace, jbtnClear, jbtnClearEntry, jbtnCloseBracket, jbtnCos, jbtnCot, jbtnCsc, jbtnCubeRoot, jbtnDecimal, jbtnDivide, jbtnEqual, jbtnExpPowerX, jbtnExpTen, jbtnFactorial, jbtnInverse, jbtnLog, jbtnMemClear, jbtnMemMinus, jbtnMemPlus, jbtnMemRecall, jbtnModulus, jbtnMultiply, jbtnNRootX, jbtnNegate, jbtnOpenBracket, jbtnRoundCeiling, jbtnRoundFloor, jbtnSec, jbtnSin, jbtnSquareRoot, jbtnSubtract, jbtnTan, jbtnXPower2, jbtnXPower3, jbtnXPowerY});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jtxtSecondary, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtPrimary, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jrdioBtnHex)
                                    .addComponent(jrdioBtnDec)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jpnlDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnConstDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(59, 59, 59)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jbtnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtnMemSet, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbtnMemClear, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jbtnMemRecall, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtnSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jbtnSin, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtnCsc, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jrdioBtnOct)
                                                .addComponent(jrdioBtnBin)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jbtnBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtnClearEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtnCos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtnSec, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtnTan, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtnCot, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jbtnLn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jbtnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jbtnExpTen, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jbtn2nd, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jbtnDMS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jbtnInt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jbtnInverse, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtnOpenBracket, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnNRootX, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnExpPowerX, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnXPowerY, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnSquareRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnRoundFloor, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnXPower2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnCloseBracket, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtnXPower3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnNegate, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnCubeRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnRoundCeiling, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbtnF, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnModulus, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnE, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnD, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnC, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtnB, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnMemPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnMultiply, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbtnA, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnMemMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jbtnClearOutput)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbtn0, jbtn1, jbtn2, jbtn3, jbtn4, jbtn5, jbtn6, jbtn7, jbtn8, jbtn9, jbtnAdd, jbtnBackspace, jbtnClear, jbtnClearEntry, jbtnCloseBracket, jbtnCos, jbtnCot, jbtnCsc, jbtnCubeRoot, jbtnDecimal, jbtnDivide, jbtnEqual, jbtnExpPowerX, jbtnExpTen, jbtnFactorial, jbtnInverse, jbtnLog, jbtnMemClear, jbtnMemMinus, jbtnMemPlus, jbtnMemRecall, jbtnModulus, jbtnMultiply, jbtnNRootX, jbtnNegate, jbtnOpenBracket, jbtnRoundCeiling, jbtnRoundFloor, jbtnSec, jbtnSin, jbtnSquareRoot, jbtnSubtract, jbtnTan, jbtnXPower2, jbtnXPower3, jbtnXPowerY});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jtxtPrimary, jtxtSecondary});

        setObjectFromProp(jbtnBackspace, miscBundle.getString(CalcConstants.BSP), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnClear, miscBundle.getString(CalcConstants.CXX), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnClearEntry, miscBundle.getString(CalcConstants.CEX), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtn0, numberBundle.getString(CalcConstants.DG0), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtn1, numberBundle.getString(CalcConstants.DG1), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtn2, numberBundle.getString(CalcConstants.DG2), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtn3, numberBundle.getString(CalcConstants.DG3), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtn4, numberBundle.getString(CalcConstants.DG4), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtn5, numberBundle.getString(CalcConstants.DG5), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtn6, numberBundle.getString(CalcConstants.DG6), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtn7, numberBundle.getString(CalcConstants.DG7), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtn8, numberBundle.getString(CalcConstants.DG8), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtn9, numberBundle.getString(CalcConstants.DG9), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnA, numberBundle.getString(CalcConstants.DGA), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnB, numberBundle.getString(CalcConstants.DGB), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnC, numberBundle.getString(CalcConstants.DGC), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnD, numberBundle.getString(CalcConstants.DGD), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnE, numberBundle.getString(CalcConstants.DGE), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnF, numberBundle.getString(CalcConstants.DGF), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnDecimal, numberBundle.getString(CalcConstants.DEC), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnNegate, operatorBundle.getString(CalcConstants.NEG), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnAdd, operatorBundle.getString(CalcConstants.ADD), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnModulus, operatorBundle.getString(CalcConstants.MOD), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnInverse, functionBundle.getString(CalcConstants.REC), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnSubtract, operatorBundle.getString(CalcConstants.SUB), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnMemClear, miscBundle.getString(CalcConstants.MCX), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnOpenBracket, operatorBundle.getString(CalcConstants.BR1), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnDivide, operatorBundle.getString(CalcConstants.DIV), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnMemRecall, miscBundle.getString(CalcConstants.MRX), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnCloseBracket, operatorBundle.getString(CalcConstants.BR2), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnMultiply, operatorBundle.getString(CalcConstants.MUL), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnMemPlus, miscBundle.getString(CalcConstants.MPX), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnFactorial, functionBundle.getString(CalcConstants.FCT), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnEqual, operatorBundle.getString(CalcConstants.EQU), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnMemMinus, miscBundle.getString(CalcConstants.MMX), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnLog, functionBundle.getString(CalcConstants.LOG), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnSin, functionBundle.getString(CalcConstants.SIN), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnCsc, functionBundle.getString(CalcConstants.CSC), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnCos, functionBundle.getString(CalcConstants.COS), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnSec, functionBundle.getString(CalcConstants.SEC), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnTan, functionBundle.getString(CalcConstants.TAN), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnCot, functionBundle.getString(CalcConstants.COT), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnExpTen, functionBundle.getString(CalcConstants.PWT), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnXPowerY, functionBundle.getString(CalcConstants.POW), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnNRootX, functionBundle.getString(CalcConstants.NRT), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnExpPowerX, functionBundle.getString(CalcConstants.ELX), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnXPower2, functionBundle.getString(CalcConstants.SQR), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnSquareRoot, functionBundle.getString(CalcConstants.SRT), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnRoundFloor, functionBundle.getString(CalcConstants.FLR), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnXPower3, functionBundle.getString(CalcConstants.CUB), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnCubeRoot, functionBundle.getString(CalcConstants.CRT), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnRoundCeiling, functionBundle.getString(CalcConstants.CLG), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnLn, functionBundle.getString(CalcConstants.NLG), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnMemSet, miscBundle.getString(CalcConstants.MSX), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnInt, functionBundle.getString(CalcConstants.INT), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnDMS, functionBundle.getString(CalcConstants.DMS), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jbtnConstDropDown, miscBundle.getString(MiscConstants.CON), MiscConstants.PIPE_DELIMITER);
        //loadSystemProperties();
        // For the jbtnConstDropDown button
        createConstDropDownMenu();
        jbtnConstDropDown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                popupMenu.show(evt.getComponent(), evt.getComponent().getSize().width/2, evt.getComponent().getSize().height/2); //30, 25
            }
        });
        setObjectFromProp(jbtn2nd, miscBundle.getString(CalcConstants.SND), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jrdioBtnHex, miscBundle.getString(CalcConstants.HEX), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jrdioBtnDec, miscBundle.getString(CalcConstants.DEC), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jrdioBtnOct, miscBundle.getString(CalcConstants.OCT), MiscConstants.PIPE_DELIMITER);
        setObjectFromProp(jrdioBtnBin, miscBundle.getString(CalcConstants.BIN), MiscConstants.PIPE_DELIMITER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnKeyActionPerformed
        //LOGGER.debug("#" + evt.toString() + "#");
        LOGGER.debug("#" + evt.getActionCommand() + "#");
        this.setCalcInfo(evt.getActionCommand());
    }//GEN-LAST:event_jbtnKeyActionPerformed

    private void jbtn2ndjbtnKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ndjbtnKeyActionPerformed
        this.set2ndKeys();
    }//GEN-LAST:event_jbtn2ndjbtnKeyActionPerformed

    private void jRdioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdioBtnActionPerformed
        this.setNumMode(evt.getActionCommand());
        this.setCalcInfo(evt.getActionCommand());
    }//GEN-LAST:event_jRdioBtnActionPerformed

    private void jbtnClearOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearOutputActionPerformed
        jtxtAreaOutput.setText("");
        jtxtPrimary.requestFocus();
    }//GEN-LAST:event_jbtnClearOutputActionPerformed

    private void jbtnConstDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConstDropDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnConstDropDownActionPerformed

/*    private void loadSystemProperties() {
        //System.out.println("In loadSystemProperties Loading system properties ... ");
        //con.LoadProp("properties/constants");
        //constantBundle
        System.out.println("In loadSystemProperties Working Directory: " + System.getProperty("user.dir"));
        System.out.println("In loadSystemProperties MiscConstants.CONSTANT_PROP_NAME: " + MiscConstants.CONSTANT_PROP_NAME);
        System.out.println("In loadSystemProperties CONSTANT_BUNDLE_NAME: " + MiscConstants.CONSTANT_BUNDLE_NAME); // + MiscConstants.PROP_EXT_NAME);
        //System.out.println("In loadSystemProperties constantBundle.getBaseBundleName: " + constantBundle.getBaseBundleName());
        //System.out.println("In loadAllUsersProperties getClass = " + getClass());
        //constantProps = new Configs(MiscConstants.CONSTANT_BUNDLE_NAME + MiscConstants.PROP_EXT_NAME);
        constantProps = new Configs(System.getProperty("user.dir") + MiscConstants.CONSTANT_PROP_NAME);
        constantProps.loadProp();
        //System.out.println("In loadSystemProperties constantProps.getPropCount(): " + constantProps.getPropCount());

    } */

    private void setObjectFromProp(JButton jButtonName, String property, String delimiter) {
        propSplitStrings = UtilsMisc.stringSplit(property, delimiter);
        switch (propSplitStrings.length) {
            case 2:
                jButtonName.setActionCommand(propSplitStrings[0]);
                jButtonName.setText(propSplitStrings[0]);
                jButtonName.setToolTipText(propSplitStrings[1]);
                break;
            case 3:
                jButtonName.setActionCommand(propSplitStrings[2]);
                jButtonName.setText(propSplitStrings[0]);
                jButtonName.setToolTipText(propSplitStrings[1]);
                break;
            default:
                LOGGER.debug("Incorrect number of parameters: " + propSplitStrings.length);
                break;
        }
        jButtonName.setFont(new Font("Arial", Font.PLAIN, 13));
    }

    private void setObjectFromProp(JRadioButton jRadioButtonName, String property, String delimiter) {
        propSplitStrings = UtilsMisc.stringSplit(property, delimiter);
        switch (propSplitStrings.length) {
            case 2:
                jRadioButtonName.setActionCommand(propSplitStrings[0]);
                jRadioButtonName.setText(propSplitStrings[0]);
                jRadioButtonName.setToolTipText(propSplitStrings[1]);
                break;
            case 3:
                jRadioButtonName.setActionCommand(propSplitStrings[2]);
                jRadioButtonName.setText(propSplitStrings[0]);
                jRadioButtonName.setToolTipText(propSplitStrings[1]);
                break;
            default:
                LOGGER.debug("Incorrect number of parameters: " + propSplitStrings.length);
                break;
        }
        jRadioButtonName.setFont(new Font("Arial", Font.PLAIN, 13));
    }

    private void setObjectFromProp(JLabel jLabelName, String property, String delimiter) {
        propSplitStrings = UtilsMisc.stringSplit(property, delimiter);
        switch (propSplitStrings.length) {
            case 2:
                jLabelName.setText(propSplitStrings[0]);
                jLabelName.setToolTipText(propSplitStrings[1]);
                break;
            case 3:
                jLabelName.setText(propSplitStrings[2]);
                jLabelName.setToolTipText(propSplitStrings[1]);
                break;
            default:
                LOGGER.debug("Incorrect number of parameters: " + propSplitStrings.length);
                break;
        }
        jLabelName.setFont(new Font("Arial", Font.PLAIN, 13));
    }

    private void setObjectFromProp(JMenuItem jMenuItemName, String property, String delimiter) {
        propSplitStrings = UtilsMisc.stringSplit(property, delimiter);
        switch (propSplitStrings.length) {
            case 2:
                jMenuItemName.setActionCommand(propSplitStrings[0]);
                jMenuItemName.setText(propSplitStrings[0] + " - " + propSplitStrings[1]);
                break;
            case 3:
                jMenuItemName.setActionCommand(propSplitStrings[0] + "|" + propSplitStrings[1]);
                jMenuItemName.setText(propSplitStrings[1] + " - " + propSplitStrings[2]);
                break;
            case 4:
                jMenuItemName.setActionCommand(propSplitStrings[0] + "|" + propSplitStrings[1] + "|" + propSplitStrings[3]);
                jMenuItemName.setText(propSplitStrings[1] + " - " + propSplitStrings[2]);
                break;
            case 5:
                jMenuItemName.setActionCommand(propSplitStrings[0] + "|" + propSplitStrings[1] + "|" + propSplitStrings[4]);
                jMenuItemName.setText(propSplitStrings[1] + " - " + propSplitStrings[2]);
                break;
            default:
                LOGGER.debug("Incorrect number of parameters: " + propSplitStrings.length);
                break;
        }
        jMenuItemName.setFont(new Font("Arial", Font.PLAIN, 13));
    }

    private JPopupMenu createConstDropDownMenu() {
        Set<String> keyset = constantBundle. keySet();
        Iterator<String> iterator = keyset.iterator();
        while (iterator.hasNext()) {
            String key = iterator.next();
            JMenuItem menuItem = new JMenuItem();
            setObjectFromProp(menuItem, (String) constantBundle.getObject(key),
                MiscConstants.PIPE_DELIMITER);
            popupMenu.add(menuItem);
            menuItem.addActionListener((java.awt.event.ActionEvent evt) -> {
                jbtnKeyActionPerformed(evt);
            });
        }

        return popupMenu;
    }

    /**
     * Takes the mouse click or key and processes it
     *
     * @param actionCmdString
     */
    public void setCalcInfo(String actionCmdString) {
        LOGGER.debug("actionCmdString #" + actionCmdString + "#");
        LOGGER.debug("keyPressed #" + keyBrdInputHandler.isKeyPressed() + "#");

        calc.inputKey(actionCmdString);
        switch (actionCmdString) {
            case CalcConstants.MSX:
                jlblMem.setEnabled(true);
                break;
            case CalcConstants.MCX:
                jlblMem.setEnabled(false);
                break;
        // Should not happen
            default:
                break;
        }

        if (calc.isTxtareaDisplayText()) {
           LOGGER.debug("OutputDigits would happen");
           jtxtAreaOutput.append(calc.getSecScreenText() + "\n" + calc.getPrmDisplayText() + "\n\n");
        }

        if (!keyBrdInputHandler.isKeyPressed() || (keyBrdInputHandler.isKeyPressed() && " C ".equals(actionCmdString))) {
            LOGGER.debug("if block\n");

            jtxtPrimary.setText(calc.getPrmDisplayText());

            if(!actionCmdString.equals(CalcConstants.BSP)) {
                jtxtSecondary.setText(calc.getSecScreenText());
            }
        }

        jtxtPrimary.requestFocus();
    }

    /**
     * Set keys based on the 2nd key enabled/disabled
     *
     */
    public void set2ndKeys() {
        LOGGER.debug("\n");

        // If is2ndclicked=true than change buttons to alternate otherwise
        // change it to original
        if (!is2ndclicked) {
            is2ndclicked = true;
            jlbl2nd.setEnabled(true);
            setObjectFromProp(jbtnDMS, functionBundle.getString(CalcConstants.DEG), MiscConstants.PIPE_DELIMITER);
            setObjectFromProp(jbtnInt, functionBundle.getString(CalcConstants.FRA), MiscConstants.PIPE_DELIMITER);
            setObjectFromProp(jbtnInverse, functionBundle.getString(CalcConstants.ABS), MiscConstants.PIPE_DELIMITER);
            setObjectFromProp(jbtnLn, functionBundle.getString(CalcConstants.LGX), MiscConstants.PIPE_DELIMITER);
            setObjectFromProp(jbtnLog, functionBundle.getString(CalcConstants.LG2), MiscConstants.PIPE_DELIMITER);
            setObjectFromProp(jbtnExpTen, functionBundle.getString(CalcConstants.PW2), MiscConstants.PIPE_DELIMITER);
            setObjectFromProp(jbtnXPowerY, functionBundle.getString(CalcConstants.NCR), MiscConstants.PIPE_DELIMITER);
            setObjectFromProp(jbtnXPower2, functionBundle.getString(CalcConstants.NC2), MiscConstants.PIPE_DELIMITER);
            setObjectFromProp(jbtnXPower3, functionBundle.getString(CalcConstants.LCM), MiscConstants.PIPE_DELIMITER);
            setObjectFromProp(jbtnSin, functionBundle.getString(CalcConstants.SNH), MiscConstants.PIPE_DELIMITER);
            setObjectFromProp(jbtnCos, functionBundle.getString(CalcConstants.CSH), MiscConstants.PIPE_DELIMITER);
            setObjectFromProp(jbtnTan, functionBundle.getString(CalcConstants.TNH), MiscConstants.PIPE_DELIMITER);
            setObjectFromProp(jbtnNRootX, functionBundle.getString(CalcConstants.NPR), MiscConstants.PIPE_DELIMITER);
            setObjectFromProp(jbtnSquareRoot, functionBundle.getString(CalcConstants.NP2), MiscConstants.PIPE_DELIMITER);
            setObjectFromProp(jbtnCubeRoot, functionBundle.getString(CalcConstants.GCD), MiscConstants.PIPE_DELIMITER);
            setObjectFromProp(jbtnCsc, functionBundle.getString(CalcConstants.CCH), MiscConstants.PIPE_DELIMITER);
            setObjectFromProp(jbtnSec, functionBundle.getString(CalcConstants.SCH), MiscConstants.PIPE_DELIMITER);
            setObjectFromProp(jbtnCot, functionBundle.getString(CalcConstants.CTH), MiscConstants.PIPE_DELIMITER);
        }
        else {
            is2ndclicked = false;
            jlbl2nd.setEnabled(false);
            setObjectFromProp(jbtnDMS, functionBundle.getString(CalcConstants.DMS), MiscConstants.PIPE_DELIMITER);
            setObjectFromProp(jbtnInt, functionBundle.getString(CalcConstants.INT), MiscConstants.PIPE_DELIMITER);
            setObjectFromProp(jbtnInverse, functionBundle.getString(CalcConstants.REC), MiscConstants.PIPE_DELIMITER);
            setObjectFromProp(jbtnLn, functionBundle.getString(CalcConstants.NLG), MiscConstants.PIPE_DELIMITER);
            setObjectFromProp(jbtnLog, functionBundle.getString(CalcConstants.LOG), MiscConstants.PIPE_DELIMITER);
            setObjectFromProp(jbtnExpTen, functionBundle.getString(CalcConstants.PWT), MiscConstants.PIPE_DELIMITER);
            setObjectFromProp(jbtnXPowerY, functionBundle.getString(CalcConstants.POW), MiscConstants.PIPE_DELIMITER);
            setObjectFromProp(jbtnXPower2, functionBundle.getString(CalcConstants.SQR), MiscConstants.PIPE_DELIMITER);
            setObjectFromProp(jbtnXPower3, functionBundle.getString(CalcConstants.CUB), MiscConstants.PIPE_DELIMITER);
            setObjectFromProp(jbtnSin, functionBundle.getString(CalcConstants.SIN), MiscConstants.PIPE_DELIMITER);
            setObjectFromProp(jbtnCos, functionBundle.getString(CalcConstants.COS), MiscConstants.PIPE_DELIMITER);
            setObjectFromProp(jbtnTan, functionBundle.getString(CalcConstants.TAN), MiscConstants.PIPE_DELIMITER);
            setObjectFromProp(jbtnNRootX, functionBundle.getString(CalcConstants.NRT), MiscConstants.PIPE_DELIMITER);
            setObjectFromProp(jbtnSquareRoot, functionBundle.getString(CalcConstants.SRT), MiscConstants.PIPE_DELIMITER);
            setObjectFromProp(jbtnCubeRoot, functionBundle.getString(CalcConstants.CRT), MiscConstants.PIPE_DELIMITER);
            setObjectFromProp(jbtnCsc, functionBundle.getString(CalcConstants.CSC), MiscConstants.PIPE_DELIMITER);
            setObjectFromProp(jbtnSec, functionBundle.getString(CalcConstants.SEC), MiscConstants.PIPE_DELIMITER);
            setObjectFromProp(jbtnCot, functionBundle.getString(CalcConstants.COT), MiscConstants.PIPE_DELIMITER);
        }

        jtxtPrimary.requestFocus();
    }

    /**
     * Sets the number system to be used. Also updates the click-ability of
     * the buttons based on the number system. Thus, if the number system is
     * BIN, buttons 3-9 are disabled.
     */
    private void setNumMode(String mode) {
        switch (mode) {
            case CalcConstants.HEX:
                setDecEnabled(true);
                setOctEnabled(true);
                setHexEnabled(true);
                break;
            case CalcConstants.DEC:
                setDecEnabled(true);
                setOctEnabled(true);
                setHexEnabled(false);
                break;
            case CalcConstants.OCT:
                setDecEnabled(true);
                setOctEnabled(false);
                setHexEnabled(false);
                break;
            case CalcConstants.BIN:
                setDecEnabled(false);
                setOctEnabled(false);
                setHexEnabled(false);
                break;
        }
        jbtnDecimal.setEnabled(mode.equals(CalcConstants.DEC));
        numMode = mode;
        calc.inputKey(mode);
    }

    /**
     * Enables all decimal number system buttons.
     */
    private void setDecEnabled(boolean b) {
        jbtn2.setEnabled(b);
        jbtn3.setEnabled(b);
        jbtn4.setEnabled(b);
        jbtn5.setEnabled(b);
        jbtn6.setEnabled(b);
        jbtn7.setEnabled(b);
    }

    /**
     * Enables all octal number system buttons.
     */
    private void setOctEnabled(boolean b) {
        jbtn8.setEnabled(b);
        jbtn9.setEnabled(b);
    }

    /**
     * Enables the hexadecimal-only buttons, that is, A-F.
     */
    private void setHexEnabled(boolean b) {
        jbtnA.setEnabled(b);
        jbtnB.setEnabled(b);
        jbtnC.setEnabled(b);
        jbtnD.setEnabled(b);
        jbtnE.setEnabled(b);
        jbtnF.setEnabled(b);
    }

    /**
     * Returns the primary display
     *
     * @return calc.getPrmDisplayText()
     */
    public JTextArea getJtxtAreaOutput() {

        return jtxtAreaOutput;
    }

    /**
     * Returns the primary display
     *
     * @return calc.getPrmDisplayText()
     */
    public String getPrmDiplayText() {

        return calc.getPrmDisplayText();
    }

    /**
     * Returns the secondary display
     *
     * @return calc.getSecScreenText()
     */
    public String getSecScreenText() {

        return calc.getSecScreenText();
    }

    /**
     * Returns the calc object
     *
     * @return calc
     */
    public Calculator getCalc() {
        return calc;
    }

    /**
     * Returns the base mode
     *
     * @return NumMode
     */
    public String getNumMode() {
        return numMode;
    }

    /**
     * Returns jtxtPrimary
     *
     * @return jtxtPrimary
     */
    public JTextField getJtxtPrimary() {
        return jtxtPrimary;
    }

    /**
     * Returns jtxtSecondary
     *
     * @return jtxtSecondary
     */
    public JTextField getJtxtSecondary() {

        return jtxtSecondary;
    }

    /**
     * Returns jbtn0
     *
     * @return jbtn0
     */
    public JButton getJbtn0() {
        return jbtn0;
    }

    /**
     * Returns jbtn1
     *
     * @return jbtn1
     */
    public JButton getJbtn1() {
        return jbtn1;
    }

    /**
     * Returns jbtn2
     *
     * @return jbtn2
     */
    public JButton getJbtn2() {
        return jbtn2;
    }

    /**
     * Returns jbtn3
     *
     * @return jbtn3
     */
    public JButton getJbtn3() {
        return jbtn3;
    }

    /**
     * Returns jbtn4
     *
     * @return jbtn4
     */
    public JButton getJbtn4() {
        return jbtn4;
    }

    /**
     * Returns jbtn5
     *
     * @return jbtn5
     */
    public JButton getJbtn5() {
        return jbtn5;
    }

    /**
     * Returns jbtn6
     *
     * @return jbtn6
     */
    public JButton getJbtn6() {
        return jbtn6;
    }

    /**
     * Returns jbtn7
     *
     * @return jbtn7
     */
    public JButton getJbtn7() {
        return jbtn7;
    }

    /**
     * Returns jbtn8
     *
     * @return jbtn8
     */
    public JButton getJbtn8() {
        return jbtn8;
    }
    /**
     * Returns jbtn9
     *
     * @return jbtn9
     */
    public JButton getJbtn9() {
        return jbtn9;
    }

    /**
     * Returns jbtnDecimal
     *
     * @return jbtnDecimal
     */
    public JButton getJbtnDecimal() {
        return jbtnDecimal;
    }

    /**
     * Returns jbtnAdd
     *
     * @return jbtnAdd
     */
    public JButton getJbtnAdd() {
        return jbtnAdd;
    }

    /**
     * Returns jbtnDivide
     *
     * @return jbtnDivide
     */
    public JButton getJbtnDivide() {
        return jbtnDivide;
    }

    /**
     * Returns jbtnEqual
     *
     * @return jbtnEqual
     */
    public JButton getJbtnEqual() {
        return jbtnEqual;
    }

    /**
     * Returns jbtnMultiply
     *
     * @return jbtnMultiply
     */
    public JButton getJbtnMultiply() {
        return jbtnMultiply;
    }

    /**
     * Returns jbtnSubtract
     *
     * @return jbtnSubtract
     */
    public JButton getJbtnSubtract() {
        return jbtnSubtract;
    }

    /**
     * Returns jbtnModulus
     *
     * @return jbtnModulus
     */
    public JButton getJbtnModulus() {
        return jbtnModulus;
    }

    /**
     * Returns jbtnLeftBracket
     *
     * @return jbtnLeftBracket
     */
    public JButton getJbtnLeftBracket() {
        return jbtnOpenBracket;
    }

    /**
     * Returns jbtnRightBracket
     *
     * @return jbtnRightBracket
     */
    public JButton getJbtnRightBracket() {
        return jbtnCloseBracket;
    }

    /**
     * Returns jbtnFactorial
     *
     * @return jbtnFactorial
     */
    public JButton getJbtnFactorial() {
        return jbtnFactorial;
    }

    /**
     * Returns jbtnClear
     *
     * @return jbtnClear
     */
    public JButton getJbtnClear() {
        return jbtnClear;
    }

    /**
     * Returns jbtnClearEntry
     *
     * @return jbtnClearEntry
     */
    public JButton getJbtnClearEntry() {
        return jbtnClearEntry;
    }

    /**
     * Returns jbtnBackspace
     *
     * @return jbtnBackspace
     */
    public JButton getJbtnBackspace() {
        return jbtnBackspace;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn2nd;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnA;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnB;
    private javax.swing.JButton jbtnBackspace;
    private javax.swing.JButton jbtnC;
    private javax.swing.JButton jbtnClear;
    private javax.swing.JButton jbtnClearEntry;
    private javax.swing.JButton jbtnClearOutput;
    private javax.swing.JButton jbtnCloseBracket;
    private javax.swing.JButton jbtnConstDropDown;
    private javax.swing.JButton jbtnCos;
    private javax.swing.JButton jbtnCot;
    private javax.swing.JButton jbtnCsc;
    private javax.swing.JButton jbtnCubeRoot;
    private javax.swing.JButton jbtnD;
    private javax.swing.JButton jbtnDMS;
    private javax.swing.JButton jbtnDecimal;
    private javax.swing.JButton jbtnDivide;
    private javax.swing.JButton jbtnE;
    private javax.swing.JButton jbtnEqual;
    private javax.swing.JButton jbtnExpPowerX;
    private javax.swing.JButton jbtnExpTen;
    private javax.swing.JButton jbtnF;
    private javax.swing.JButton jbtnFactorial;
    private javax.swing.ButtonGroup jbtnGrpBase;
    private javax.swing.JButton jbtnInt;
    private javax.swing.JButton jbtnInverse;
    private javax.swing.JButton jbtnLn;
    private javax.swing.JButton jbtnLog;
    private javax.swing.JButton jbtnMemClear;
    private javax.swing.JButton jbtnMemMinus;
    private javax.swing.JButton jbtnMemPlus;
    private javax.swing.JButton jbtnMemRecall;
    private javax.swing.JButton jbtnMemSet;
    private javax.swing.JButton jbtnModulus;
    private javax.swing.JButton jbtnMultiply;
    private javax.swing.JButton jbtnNRootX;
    private javax.swing.JButton jbtnNegate;
    private javax.swing.JButton jbtnOpenBracket;
    private javax.swing.JButton jbtnRoundCeiling;
    private javax.swing.JButton jbtnRoundFloor;
    private javax.swing.JButton jbtnSec;
    private javax.swing.JButton jbtnSin;
    private javax.swing.JButton jbtnSquareRoot;
    private javax.swing.JButton jbtnSubtract;
    private javax.swing.JButton jbtnTan;
    private javax.swing.JButton jbtnXPower2;
    private javax.swing.JButton jbtnXPower3;
    private javax.swing.JButton jbtnXPowerY;
    private javax.swing.JLabel jlbl2nd;
    private javax.swing.JLabel jlblMem;
    private javax.swing.JPanel jpnlDisplay;
    private javax.swing.JRadioButton jrdioBtnBin;
    private javax.swing.JRadioButton jrdioBtnDec;
    private javax.swing.JRadioButton jrdioBtnHex;
    private javax.swing.JRadioButton jrdioBtnOct;
    private javax.swing.JTextArea jtxtAreaOutput;
    private javax.swing.JTextField jtxtPrimary;
    private javax.swing.JTextField jtxtSecondary;
    // End of variables declaration//GEN-END:variables

}
